name: golang-setup

on:
  push:
    branches: [ "master", "feature/ci-cd-tests" ]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go mod download
      - name: Run unit tests
        run: go test ./... -coverprofile cover.out && go tool cover -func cover.out